  name: screenshot

  on:
    push:
      branches:
        - "main"
  jobs:
    screenshot-no-width:
      name: screenshot
      runs-on: ubuntu-latest
  
      steps:
      - name: Screenshot Website
        id: screenshot-generator
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://www.danecjensen.com/2023/08/11/building-in-public.html
          destination: screenshot.png
          width: 992
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: screenshot
          path: ~/download/path
    
      # - name: Checkout
      #   uses: swinton/screenshot-website@ebee86398fa0b725f4080fd8a016d845211dd279
  
      # - name: Capture Screenshot
      #   id: screenshot
      #   uses: ./
      #   with:
      #     source: 
      #     # destination: "screenshot.png"
      #     full-page: true
  # # You may pin to the exact commit or the version.
  # # uses: swinton/screenshot-website@ebee86398fa0b725f4080fd8a016d845211dd279
  # uses: swinton/screenshot-website@v1.0.0
  # with:
  #   # Source of the content to be captured, may be a URL or HTML content
  #   source: https://www.danecjensen.com/2023/08/11/building-in-public.html
  #   # The destination filename the captured website will be written to
  #   destination: # optional, default is screenshot.png
