  name: screenshot-website
  # You may pin to the exact commit or the version.
  # uses: swinton/screenshot-website@ebee86398fa0b725f4080fd8a016d845211dd279
  uses: swinton/screenshot-website@v1.0.0
  with:
    # Source of the content to be captured, may be a URL or HTML content
    source: https://www.danecjensen.com/2023/08/11/building-in-public.html
    # The destination filename the captured website will be written to
    destination: # optional, default is screenshot.png
